import classes from "./ProgrammingIcons.module.css";
import nodeImage from '../tools/nodejs.png'
export default function ImgList() {
  return (
    <div className={classes.container}>
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg"
        alt="HTML"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg"
        alt="HTML"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
        alt="JS"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jquery/jquery-original-wordmark.svg"
        alt="jQuery"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
        alt="react.JS"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg"
        alt="Sass"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-plain-wordmark.svg"
        alt="Bootstrap"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original-wordmark.svg"
        alt="Git"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg"
        alt="firebase"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg"
        alt="material ui"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original-wordmark.svg"
        alt="node"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original-wordmark.svg"
        alt="mongodb"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg"
        alt="tensorflow"
      />
      <img
        className={classes.img}
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original-wordmark.svg"
        alt="python"
      />
      
    </div>
  );
}
